[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tessax"        
version = "0.1.0"         
description = "automatic indexing library"
readme = "README.md"       
requires-python = ">=3.12.10"  
authors = [
  {name = "Aron Kauhs", email = "aronkauhs@outlook.com"}
]

dependencies = [
    "requests>=2.31.0",
    "beautifulsoup4>=4.14.3",
    "pydantic>=2.12.5",
    "transformers>=5.3.0",
    "sentence-transformers>=5.2.3",
    "psycopg>=3.3.3",
    "pgvector>=0.4.2",
    "psycopg[binary]>=3.3.3", 
]

[project.optional-dependencies]
dev = [
    "pytest>=9.0.2",
    "black>=26.3.1",
    "ruff>=0.15.6",
]

[tool.pytest.ini_options]
testpaths = ["tests"]