CREATE EXTENSION vector;

CREATE TABLE html_nodes(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	parent_id INTEGER REFERENCES html_nodes(id) ON DELETE CASCADE,
	content text ,
	embedding vector(1024) 
);

CREATE OR REPLACE FUNCTION rrf_score(rank bigint, rrf_k int DEFAULT 50)
RETURNS numeric
LANGUAGE SQL
IMMUTABLE PARALLEL SAFE
AS $$
    SELECT COALESCE(1.0 / ($1 + $2), 0.0);
$$;s